github: abhishek01-github
---
---
execution:
  scenario:
    script: path/to/your/jmeter/testplan.jmx
  concurrency: 10
  ramp-up: 1m
  hold-for: 5m
  iterations: 100

reporting:
  - module: final-stats
    summary: true
    percentiles: [50, 95, 99]
  - module: junit-xml

modules:
  jmeter:
    properties:
      log_level.jmeter: INFO
