github: abhishek01-github
---
execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 5m
  scenario: my_test_scenario

scenarios:
  my_test_scenario:
    requests:
    - url: https://example.com
      method: GET
