github: abhishek01-github
---
execution:
  scenario:
    script: my_test_script.jmx
  concurrency: 10
  ramp-up: 5m
  hold-for: 10m
  iterations: 100

modules:
  jmeter:
    properties:
      log_level.jmeter: DEBUG

